version: '3.3'
services:
  app:
    build: .
    depends_on:
      - traindb
    environment:
      POSTGRES_DB: traindb
      POSTGRES_PASSWORD: password
    volumes:
      - ./TrainSystem:/app/
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
  traindb:
    image: postgres
    environment:
      - POSTGRES_DB=TrainDemo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
