version: '3.3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=TrainSystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
#    volumes:
#      - ./database/init.sql:/docker-entrypoint-initdb.d