version: '3.3'
services:
  dv8:
    build: dv8
    volumes:
      - .:/app/
    command: tail -F anything
  app:
    build: .
    depends_on:
      - traindb
    environment:
      POSTGRES_DB: TrainDemo
      POSTGRES_PASSWORD: password
    volumes:
      - .:/app/
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
  traindb:
    image: postgres
    environment:
      - POSTGRES_DB=TrainDemo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./database/init_tables.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/order_tbl.sql:/docker-entrypoint-initdb.d/2-schema.sql
      - ./database/user_tbl.sql:/docker-entrypoint-initdb.d/3-schema.sql
      - ./database/init_data.sql:/docker-entrypoint-initdb.d/4-data.sql
