@startuml
title Checkout Sequence
hide footbox
autoactivate on

actor "Browser" as client
participant "Spring Boot Framework" as SB

client -> SB : POST("/checkout")

SB -> CheckoutController : viewCheckoutForm()
note left
Exact interaction between
Spring Boot Framework
and Controllers hidden
within Spring Boot
end note

CheckoutController -> Billing : Billing()
return billing

return "checkout/checkout_form"
return "checkout/checkout_form"

client-> SB : POST("/checkout/submit")
SB -> CheckoutController : submitOrder
CheckoutController -> Billing : getCreditCard()
return billingCreditCard

alt billingCreditCard == NULL
   CheckoutController -> CheckoutError : CheckoutError(errorMessage)
   return checkoutError
'   CheckoutController --> SB : "redirect:/checkout"
end

CheckoutController -> CartService : getOrCreateCart
return cart
CheckoutController -> Order : Order(cart, billing)
return order

CheckoutController -> CheckoutController : resetCart()
return
return
return "checkout/checkout_sucesss"

@enduml