@startuml
title Checkout Sequence
!include util.puml
hide footbox
autoactivate on

actor "Browser" as client
participant "Spring Boot Framework" as SB
== View Checkout Form ==
client -> SB : POST("/checkout")

SB -> CheckoutController : viewCheckoutForm(Model model)
MAKE_NOTE()

CheckoutController -> Billing : Billing()
return billing

CheckoutController -> Model : addAttribute(billing)
return

return "checkout/checkout_form"
return checkout/checkout_form.html

== Submit Checkout Form ==
client-> SB : POST("/checkout/submit")
SB -> CheckoutController : submitOrder(Model model)
MAKE_NOTE()
CheckoutController -> Billing : getCreditCard()
return billingCreditCard

alt billingCreditCard == NULL
   CheckoutController -> CheckoutError : CheckoutError(errorMessage)
   note left
   User is
   redirected to
   /checkout
   end note

   return checkoutError

'   CheckoutController --> SB : "redirect:/checkout"
end

CheckoutController -> CartService : getOrCreateCart
return cart
CheckoutController -> Order : Order(cart, billing)
return newOrder

CheckoutController -> CheckoutController : resetCart()
return

CheckoutController -> Model : addAttribute(newOrder)
return

return "checkout/checkout_success"
return checkout/checkout_success.html

@enduml