@startuml
!include util.puml
title Manage Itineraries \n This is purely notional and not implemented

autoactivate on
actor "Browser" as C
participant "Spring Boot Framework" as SBF
participant "AdminController" as controller
participant "AdminService" as service


==View Itineraries As Admin==
C -> SBF : GET("/admin/trip/view")
SBF -> controller : viewTrips(Model model)
MAKE_NOTE()
controller -> service : getTrips()
service -> TripService : getAllTrips()
return trips
return trips
controller -> Model : addAttribute(trips)
return
return "admin/view_trips"
return admin/view_trips.html

==Add Stop==
C -> SBF : POST("/admin/trip/edit_trip")
SBF -> controller : addStop()
MAKE_NOTE()
controller -> service : addStop()
service -> TripService : addStop()
TripService -> TripService : editTrip()
return trip
return trip
return trip
controller -> Model : addAttribute(trip)
return
return "admin/edit_trip"
return admin/edit_trip.html

==Manage Available Tickets==
C -> SBF : POST("/admin/trip/train")
SBF -> controller : editTrain()
MAKE_NOTE()
controller -> service : editTrain()
service -> TripService : editTrain()
return train
return train
controller -> Model : addAttribute(train)
return
return "admin/edit_train"
return admin/edit_train.html


==Edit Trip Info==
C -> SBF : POST("/admin/trip/edit_trip")
SBF -> controller : editTripInfo()
MAKE_NOTE()
controller -> service : editTripInfo()
service -> TripService : editTripInfo()
TripService -> TripService : editTrip()
return trip
return trip
return trip
controller -> Model : addAttribute(trip)
return
return "admin/edit_trip"
return admin/edit_trip.html
@enduml